class Emojis:
    ARROW = "➡️"
    BOT = "🤖"
    ERROR = "❌"
    INFO = "ℹ️"
    LOADING = "⏳"
    LOCK = "🔒"
    REST = "⚙️"
    SERVER = "🖥️"
    SLASH = "⚡"
    SUCCESS = "✅"
    UNLOCK = "🔓"
    USER = "👤"
    WS = "🌐"
